{{- define "mgmt.portainer.values" }}
domain: {{ .Values.domain }}
storageClassName: {{.Values.storageClassName }}
gateway: {{ .Values.gateway }}
portainer:
  persistence:
    existingClaim: portainer-data
{{- end }}

{{- if eq .Values.portainer.enabled true }}
{{- $value := include "mgmt.portainer.values" . | fromYaml }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  project: {{ .Values.project }}
  source:
    path: charts/portainer
    repoURL: "{{ .Values.repo }}"
    helm:
      values: {{ $value | toJson | quote }}
    targetRevision: "{{ .Values.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
