
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}"
spec:
  hosts:
  - "{{ .Values.subdomain }}.{{ .Values.domain }}"
  gateways:
  - "{{ .Values.gateway }}"
  http:
  - route:
    - destination:
        host: "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
        port:
          number: 80
